### ISSUE TITLE
op-node: improve finality-signal handling

### ISSUE THREAD

**Issue by protolambda** [ethereum-optimism/optimism#10724]
Immediately processing of finalization, with the necessary API check(s), upon receiving the finality call is not desired: it couples the subsequent calls directly to the signal, and the error-cases cannot be handled. Currently it still retains the signal, and can then later revisit the finalization attempt, but that should be the only way finalization happens.

Additionally, one of the two sanity checks applies to the L1 finality signal that was received, but does not add any assurances: the signal is already trusted, and the trust-model of the finality check is no different. This check can thus be removed. To remove, the action-test assertion that relies on faking a finality signal should be removed.

**Comment by protolambda** [comment]
This was fixed with the event-refactor. Closing as stale.

**Comment by ajsutton** [comment]
Reopening this as there's still a TODO which suggests it wasn't actually fixed with the event-refactor:
https://github.com/ethereum-optimism/optimism/blob/fde839a549091294f19ed604c88e56903630de88/op-node/rollup/finality/finalizer.go#L227

If this change isn't required can we please remove the TODO?

**Comment by protolambda** [comment]
@ajsutton that's a sanity check, which I think is better to keep around than remove. I'll remove the TODO, thanks for flagging!

**Comment by protolambda** [comment]
https://github.com/ethereum-optimism/optimism/pull/14620
