### ISSUE TITLE
OP-Deployer won't deploy to Holesky testnet

### ISSUE THREAD

**Issue by ZakAyesh** [ethereum-optimism/optimism#12859]
**Bug Description**
op-deployer won't deploy to Ethereum's Holesky testnet, it produces the following error:

```
Application failed: error getting superchain config: unsupported chain ID: 17000
```

**Steps to Reproduce**
Ran command below:

```
op-deployer bootstrap opcm --l1-rpc-url endpoint --private-key prKey --artifacts-locator ­tag://op-contracts/v1.6.0 
```

**Environment Information:**
MacOS Sonoma version 14.4

Monorepo Git HEAD Commit Hash: b6bd58e

**Logs:**
```
op-deployer bootstrap opcm --l1-rpc-url endpoint --private-key prKey --artifacts-locator ­tag://op-contracts/v1.6.0 
INFO [11-06|17:45:29.977] artifacts download progress              current=4096 total=54,132,933
INFO [11-06|17:45:30.977] artifacts download progress              current=39,353,107 total=54,132,933
Application failed: error getting superchain config: unsupported chain ID: 17000
```

---

⚠️ **Notice:** Issues that do not include the following sections will be subject to closure:
- Bug Description
- Steps to Reproduce
- Environment Information

Please ensure all required sections are filled out accurately to expedite the debugging process and improve issue resolution efficiency.

**Comment by priyanshuthapliyal** [comment]
Also experiencing same issue with Holesky.

`INFO [11-19|17:08:52.416] artifacts download progress              current=4096 total=54,132,933
INFO [11-19|17:08:53.436] artifacts download progress              current=199,444 total=54,132,933
INFO [11-19|17:08:54.436] artifacts download progress              current=2,957,312 total=54,132,933
INFO [11-19|17:08:55.440] artifacts download progress              current=6,752,022 total=54,132,933
INFO [11-19|17:08:56.441] artifacts download progress              current=10,553,110 total=54,132,933
INFO [11-19|17:08:57.442] artifacts download progress              current=14,354,198 total=54,132,933
INFO [11-19|17:08:58.445] artifacts download progress              current=17,991,446 total=54,132,933
INFO [11-19|17:08:59.445] artifacts download progress              current=21,939,990 total=54,132,933
INFO [11-19|17:09:00.446] artifacts download progress              current=25,691,926 total=54,132,933
INFO [11-19|17:09:01.449] artifacts download progress              current=29,493,014 total=54,132,933
INFO [11-19|17:09:02.456] artifacts download progress              current=33,326,870 total=54,132,933
INFO [11-19|17:09:03.461] artifacts download progress              current=36,833,046 total=54,132,933
INFO [11-19|17:09:04.464] artifacts download progress              current=40,863,510 total=54,132,933
INFO [11-19|17:09:05.465] artifacts download progress              current=44,664,598 total=54,132,933
INFO [11-19|17:09:06.495] artifacts download progress              current=47,023,894 total=54,132,933
INFO [11-19|17:09:07.495] artifacts download progress              current=50,337,558 total=54,132,933
INFO [11-19|17:09:08.502] artifacts download progress              current=53,380,886 total=54,132,933
Application failed: error getting superchain config: unsupported chain ID: 17000`

**Comment by ferranbt** [comment]
Hey, I am also having this issue with a local chain deployed with [builder-playground](https://github.com/flashbots/builder-playground)

```
$ cd builder-playground 
$ go run main.go
```

Now, use op-deployer:

```
$ go run main.go init --l1-chain-id 1337 --l2-chain-ids 2
$ go run main.go apply --l1-rpc-url http://localhost:8545 --private-key <valid priv key>
...
Application failed: error in pipeline stage apply: error getting superchain config: unsupported chain ID: 1337
```

**Comment by mslipper** [comment]
This should be fixed now. Note that if you decide to deploy to a new chain like Holesky, you will get a big warning reminding you that you won't necessarily be running governance approved versions of the contracts. This is due to a limitation of our smart contract deployment process.

**Comment by TimTinkers** [comment]
I see you've reverted the warning in https://github.com/ethereum-optimism/optimism/pull/13231/files. Is this a WONTFIX now?

Can we have this enabled again, perhaps behind a very-very-scary configuration flag? Manually patching the deployer to allow for Holesky testing is annoying.

**Comment by priyanshuthapliyal55** [comment]
I am still getting the same error that error `getting superchain config: unsupported chain ID: 17000`. I don't think this has been fixed?
