### ISSUE TITLE
bug: `op-node` shouldn't call `debug_chainConfig` on auth-rpc when working with custom chain configs

### ISSUE THREAD

**Issue by 0x416e746f6e** [ethereum-optimism/optimism#14396]
**Bug Description**

1. As of #14179 `op-node`, when using non-standard (non superchain) chain IDs, is trying to call `debug_chainConfig` method against _authrpc_ port of the EL.

    See:

    - https://github.com/ethereum-optimism/optimism/blob/v1.11.0/op-node/node/node.go#L464-L466

2. However, `debug` namespace is _not_ implemented by authrpc.

    See:  

    - https://github.com/ethereum-optimism/op-geth/blob/v1.101500.0/node/defaults.go#L52
    - https://github.com/ethereum-optimism/op-geth/blob/v1.101500.0/node/node.go#L433-L436

3. Consequently the `op-node` deterministically fails on start with something like:

    ```text
    failed to setup: unable to create the rollup node: failed to init L2: failed to load or fetch chain config for id NNNN: fetching: Method not found
    ```

**Steps to Reproduce**

1. Try to use custom chain config (via `rollup.json`).

**Expected behavior**

No failure when custom chain config is used.

**Environment Information:**

- Ubuntu 24.04.1 LTS
- op-node v1.11.0

---

⚠️ **Notice:** Issues that do not include the following sections will be subject to closure:
- Bug Description
- Steps to Reproduce
- Environment Information

Please ensure all required sections are filled out accurately to expedite the debugging process and improve issue resolution efficiency.

**Comment by jcortejoso** [comment]
You need to add `chain_op_config` field to the chain `rollup.json`:

```
  "chain_op_config": {
    "eip1559Elasticity": 6,
    "eip1559Denominator": 50,
    "eip1559DenominatorCanyon": 250
  }
```

**Comment by 0x416e746f6e** [comment]
@jcortejoso thanks!  that helped to unblock.

(still, I think it shouldn't be calling for `debug_chainConfig` on authrpc port => either el-clients `op-geth`/`op-reth` should be updated, or another port configured for "plain" rpc calls, or just fail on the spot indicating what's wrong with `rollup.json`)

**Comment by sebastianst** [comment]
I agree that we should just remove the rpc call, it was misguided. We should just require the correct `rollup.json`. The latest release notes mention this breaking change. We will remove the rpc call in the next release.

**Comment by protolambda** [comment]
I just merged https://github.com/ethereum-optimism/op-geth/pull/512 in op-geth, so the debug namespace can be made available on the auth RPC.
This is mostly a work-around for chains that need to handle this chain-config / rollup config situation.
I agree that we likely want to remove this in the next (or some later) release.

**Comment by pc-quiknode** [comment]
@protolambda @zhiqiangxu 
https://github.com/ethereum-optimism/op-geth/pull/512 doesn't seem to work.
I am still getting the error with `v1.101500.1`

**Comment by zhiqiangxu** [comment]
@pc-quiknode did you enable `debug` namespace in the http api?

**Comment by pc-quiknode** [comment]
> @pc-quiknode did you enable `debug` namespace in the http api?

Yes
```
--http.api=admin,debug,eth,net,web3
```
